echo "# Pc-Virtual-Gratis" >> README.md 
git init 
git add README.md 
git commit -m "primeiro commit" 
git branch -M main 
git remote add origin https://github.com/gta019048-web/Pc-Virtual-Gratis.git
 git push -u origin main
